# Generated by Django 6.1.1 on 2026-09-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='commissionrule',
            options={'ordering': ['weekday'], 'verbose_name': 'Regra de Comissão', 'verbose_name_plural': 'Regras de Comissão'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['code'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_time'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Item da Venda', 'verbose_name_plural': 'Itens da Venda'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['name'], 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
